### ISSUE TITLE
Nodejs Support

### ISSUE THREAD

**Issue by treveshan** [rexshijaku/PDFBarcodeJS#1]
Hi 

Is there any documentation on Nodejs support ? Will be really awesome if you could help me out.

**Comment by rexshijaku** [comment]
Hi @treveshan , I hope you're doing well

I realized that some scripts were not able to run on Node. I had to fix a lot of things in order to add Node.js support for this package. Check the updated documentation (search for 'Node Usage'), I just added it. I hope it helps.

**Comment by treveshan** [comment]
@rexshijaku thank you so much. Still having some issues but i think its on my side

**Comment by rexshijaku** [comment]
@treveshan You're welcome, for anything do not hesitate to write again.
