### ISSUE TITLE
QR Code Support

### ISSUE THREAD

**Issue by celevra** [rexshijaku/PDFBarcodeJS#3]
Hi,

thanks for that great library
is it possible to implement QR Code Support also?

regards

Celevra

**Comment by rexshijaku** [comment]
Hi @celevra , thank you!
I will consider it.

**Comment by monxas** [comment]
Any news on this? I'd be very interested in qrcode support.

**Comment by rexshijaku** [comment]
Hi @celevra and @monxas . I decided that it would be more convenient to add the QR Code support on a separate project. You may find the it here  https://github.com/rexshijaku/pdf-qr.js. Feel free to report any issue!

**Comment by celevra** [comment]
awesome, thank you!
